# 320_Fine_Tuning_Custom_Datasets

In [2]:
!pip install transformers

Collecting transformers
  Downloading transformers-4.9.2-py3-none-any.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 9.4 MB/s
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.62.0)
Collecting huggingface-hub==0.0.12
  Downloading huggingface_hub-0.0.12-py3-none-any.whl (37 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.6.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from transformers) (21.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.19.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2019.12.20)
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 52.5 MB/s
Collecting pyyaml>=5.1
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     |████████████████████████████████| 636 kB 35.6 MB/s
Collecting sacremoses
  Downloading sacremoses-0.0.45-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 49.1 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.0.12)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from huggingface-hub==0.0.12->transformers) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->transformers) (2.4.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2021.5.30)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (7.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.15.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.0.1)
Installing collected packages: tokenizers, sacremoses, pyyaml, huggingface-hub, transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed huggingface-hub-0.0.12 pyyaml-5.4.1 sacremoses-0.0.45 tokenizers-0.10.3 transformers-4.9.2

In [3]:
from transformers import BertTokenizer
from transformers import BertForSequenceClassification, Trainer, TrainingArguments
import torch.nn.functional as F
import tensorflow as tf
import pandas as pd

In [4]:
DATA_TRAIN_PATH = tf.keras.utils.get_file("ratings_train.txt", 
                                "https://raw.github.com/ironmanciti/NLP_lecture/master/data/naver_movie/ratings_train.txt")
DATA_TEST_PATH = tf.keras.utils.get_file("ratings_test.txt", 
                                 "https://raw.github.com/ironmanciti/NLP_lecture/master/data/naver_movie/ratings_test.txt")

Downloading data from https://raw.github.com/ironmanciti/NLP_lecture/master/data/naver_movie/ratings_train.txt
14786560/14778808 [==============================] - 0s 0us/step
14794752/14778808 [==============================] - 0s 0us/step
Downloading data from https://raw.github.com/ironmanciti/NLP_lecture/master/data/naver_movie/ratings_test.txt
4947968/4943336 [==============================] - 0s 0us/step
4956160/4943336 [==============================] - 0s 0us/step

In [5]:
train_data = pd.read_csv(DATA_TRAIN_PATH, delimiter='\t')
print(train_data.shape)
train_data.head()

(150000, 3)

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [6]:
train_data.dropna(inplace=True)
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149995 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        149995 non-null  int64
 1   document  149995 non-null  object
 2   label     149995 non-null  int64
dtypes: int64(2), object(1)
memory usage: 4.6+ MB

In [7]:
test_data = pd.read_csv(DATA_TEST_PATH, delimiter='\t')
print(test_data.shape)
test_data.head()

(50000, 3)

        id                                           document  label
0  6270596                                                굳 ㅋ      1
1  9274899                               GDNTOPCLASSINTHECLUB      0
2  8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3  6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4  6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0

In [8]:
test_data.dropna(inplace=True)
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49997 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        49997 non-null  int64
 1   document  49997 non-null  object
 2   label     49997 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.5+ MB

In [9]:
df_train = train_data.sample(n=5000, random_state=1)
df_test = test_data.sample(n=500, random_state=1)
print(df_train.shape)
print(df_test.shape)

(5000, 3)
(500, 3)

In [10]:
df_train['label'].value_counts()

0    2520
1    2480
Name: label, dtype: int64

In [11]:
X_train = df_train['document'].values.tolist()
y_train = df_train['label'].values

X_test = df_test['document'].values.tolist()
y_test = df_test['label'].values

### 1. Call the pre-trained model
### 2. Call the tokenizer
이제 토큰화를 처리해 보겠습니다. 우리는 사전 훈련된 DistilBert를 사용하여 분류기를 훈련할 것이므로 DistilBert 토크나이저를 사용합시다.

In [12]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
# tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

In [13]:
train_encodings = tokenizer(X_train, truncation=True, padding=True)
test_encodings = tokenizer(X_test, truncation=True, padding=True)

In [14]:
train_encodings.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

### Convert encodings to Tensors

이제 레이블과 인코딩을 Dataset 개체로 변환해 보겠습니다. PyTorch에서 이것은 `torch.utils.data.Dataset` 객체를 서브클래싱하고 `__len__` 및 `__getitem__`을 구현하여 수행됩니다. TensorFlow에서 입력 인코딩과 레이블을 `from_tensor_slices` 생성자 메서드에 전달합니다. 
배치 인코딩의 각 키가 우리가 훈련할 모델의 `DistilBertForSequenceClassification.forward` 메소드의 명명된 매개변수에 해당하도록 쉽게 배치할 수 있습니다.

In [54]:
import torch

class IMDbDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

train_dataset = IMDbDataset(train_encodings, y_train)
test_dataset = IMDbDataset(test_encodings, y_test)

이제 데이터 세트가 준비되었으므로 🤗 `Trainer`/`TFTrainer` 또는 기본 PyTorch/TensorFlow를 사용하여 모델을 미세 조정할 수 있습니다. [training](https://huggingface.co/transformers/training.html)을 참조하세요.

- Training warmup steps :  

    - 이는 일반적으로 설정된 수의 훈련 단계(워밍업 단계)에 대해 매우 낮은 학습률을 사용한다는 것을 의미합니다. 워밍업 단계 후에 "일반" 학습률 또는 학습률 스케줄러를 사용합니다. 또한 워밍업 단계 수에 따라 학습률을 점진적으로 높일 수 있습니다.

- weight_decay : 가중치 감쇠. L2 regularization

In [16]:
training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=2,              # total number of training epochs
    per_device_train_batch_size=8,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
)

### Training

In [17]:
model = BertForSequenceClassification.from_pretrained('bert-base-multilingual-cased')

trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=test_dataset             # evaluation dataset
)

trainer.train()

Downloading:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
***** Running training *****
  Num examples = 5000
  Num Epochs = 2
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 1250

Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin


Training completed. Do not forget to share your model on huggingface.co/models =)

TrainOutput(global_step=1250, training_loss=0.5410470478057862, metrics={'train_runtime': 190.3097, 'train_samples_per_second': 52.546, 'train_steps_per_second': 6.568, 'total_flos': 616666536000000.0, 'train_loss': 0.5410470478057862, 'epoch': 2.0})

In [18]:
trainer.evaluate(test_dataset)

***** Running Evaluation *****
  Num examples = 500
  Batch size = 16

{'epoch': 2.0,
 'eval_loss': 0.4788724482059479,
 'eval_runtime': 1.6588,
 'eval_samples_per_second': 301.426,
 'eval_steps_per_second': 19.291}

In [19]:
prediction = trainer.predict(test_dataset)
prediction

***** Running Prediction *****
  Num examples = 500
  Batch size = 16

PredictionOutput(predictions=array([[ 0.8485763 , -0.7297784 ],
       [ 1.1591598 , -0.961922  ],
       [ 1.2761818 , -1.09666   ],
       [ 1.6204393 , -1.5558041 ],
       [-0.42283344,  0.5847641 ],
       [ 1.6240362 , -1.5701936 ],
       [-0.15356077,  0.2954778 ],
       [ 0.9486881 , -0.76435316],
       [-1.6589617 ,  1.6999959 ],
       [ 1.0179737 , -0.83315307],
       [-1.667927  ,  1.7211415 ],
       [ 0.00684868,  0.15477955],
       [ 1.563712  , -1.460004  ],
       [ 0.9829624 , -0.8271281 ],
       [-0.08028116,  0.20641445],
       [ 1.2602435 , -1.0579846 ],
       [ 1.6224183 , -1.5728186 ],
       [-1.342532  ,  1.4737881 ],
       [ 1.5970389 , -1.531518  ],
       [ 0.32985806, -0.17224623],
       [ 1.6145662 , -1.5677181 ],
       [ 1.3626186 , -1.1987771 ],
       [-0.03956339,  0.20842141],
       [ 0.00471243,  0.16170405],
       [ 1.5247077 , -1.4382635 ],
       [ 1.1031789 , -0.93138635],
       [ 0.61438775, -0.46630186],
       [-1.5085644 ,  1.5305053 ],
       [ 0.887999  , -0.7446815 ],
       [ 0.84680593, -0.7094866 ],
       [ 1.6077529 , -1.5451566 ],
       [ 1.5947374 , -1.5524505 ],
       [-1.5034658 ,  1.5135772 ],
       [-1.3731575 ,  1.3929551 ],
       [ 1.5993062 , -1.5573784 ],
       [ 1.6132959 , -1.5561305 ],
       [ 0.7028202 , -0.5896434 ],
       [ 1.6184536 , -1.557495  ],
       [ 0.32031745, -0.16179155],
       [ 0.36613846, -0.18493277],
       [ 0.25242454, -0.08131009],
       [-1.6137071 ,  1.6626897 ],
       [-0.7573998 ,  0.88255155],
       [-1.6234535 ,  1.6478537 ],
       [ 1.147196  , -0.97558886],
       [-1.6333958 ,  1.6994292 ],
       [-1.655302  ,  1.6923131 ],
       [ 1.6219689 , -1.5746709 ],
       [-0.589201  ,  0.7344865 ],
       [-1.5371293 ,  1.5652362 ],
       [-1.5464742 ,  1.5528167 ],
       [-1.6431023 ,  1.6748047 ],
       [ 0.5987737 , -0.43515006],
       [ 1.5596735 , -1.4532346 ],
       [ 1.5039542 , -1.3643494 ],
       [ 1.5266473 , -1.4269104 ],
       [-0.23699817,  0.38100594],
       [ 1.620354  , -1.5700798 ],
       [-1.5992111 ,  1.6388098 ],
       [-1.530254  ,  1.5566688 ],
       [ 1.5890012 , -1.5062762 ],
       [-1.3811787 ,  1.4735395 ],
       [ 0.75600094, -0.5636961 ],
       [ 0.15911178,  0.01003513],
       [-0.72960365,  0.7893305 ],
       [ 1.5944179 , -1.5204613 ],
       [ 1.6279719 , -1.5883759 ],
       [-0.40999967,  0.54255974],
       [-0.5314456 ,  0.63798094],
       [-0.09027077,  0.22080998],
       [ 1.622998  , -1.591162  ],
       [-0.15671323,  0.26076323],
       [ 1.4668489 , -1.3392061 ],
       [-0.31131375,  0.4244334 ],
       [-1.5582681 ,  1.5912148 ],
       [-0.46106383,  0.5777778 ],
       [-1.5082065 ,  1.5301875 ],
       [ 1.6211456 , -1.5835942 ],
       [ 1.4195825 , -1.2496551 ],
       [ 0.06345595,  0.04380738],
       [-1.362259  ,  1.4050496 ],
       [-1.6481982 ,  1.6843086 ],
       [-1.6594926 ,  1.7001535 ],
       [-0.3122899 ,  0.48163247],
       [-1.6320418 ,  1.6786226 ],
       [ 0.43134895, -0.27636507],
       [-0.8344064 ,  0.94615304],
       [ 1.5747656 , -1.4961761 ],
       [ 0.25272512, -0.12103071],
       [-0.71830726,  0.82181376],
       [ 0.9657399 , -0.77650785],
       [-1.355107  ,  1.4541887 ],
       [ 1.5767614 , -1.490981  ],
       [-1.1981155 ,  1.3493189 ],
       [ 1.6042637 , -1.5349447 ],
       [-0.7528688 ,  0.77136946],
       [-0.27230197,  0.43584156],
       [ 0.12945779,  0.01205032],
       [ 1.6205629 , -1.5869418 ],
       [ 0.98920906, -0.80325884],
       [-1.1386145 ,  1.2773031 ],
       [-0.36599582,  0.4902365 ],
       [-1.6373867 ,  1.6848081 ],
       [ 1.3613502 , -1.2126184 ],
       [ 1.614556  , -1.5721287 ],
       [ 0.17311294, -0.04005444],
       [-1.3116242 ,  1.4345458 ],
       [ 1.6100128 , -1.563857  ],
       [ 1.4233141 , -1.2628211 ],
       [ 0.41618103, -0.29471946],
       [-1.3183306 ,  1.413668  ],
       [ 1.3998767 , -1.2330593 ],
       [-0.5763187 ,  0.6688274 ],
       [-1.2688893 ,  1.3716255 ],
       [-0.51312387,  0.5950263 ],
       [ 0.04288942,  0.09471399],
       [ 0.08452621,  0.04916897],
       [-0.81861806,  0.9409762 ],
       [ 1.1173035 , -0.926741  ],
       [ 0.9235553 , -0.7517228 ],
       [-0.05361318,  0.16916595],
       [-1.4160157 ,  1.4590493 ],
       [-0.16267575,  0.26906353],
       [-0.5707121 ,  0.71071506],
       [ 1.6252352 , -1.5914408 ],
       [ 0.11388973,  0.02553   ],
       [ 0.01349704,  0.12115623],
       [-1.6341954 ,  1.6926883 ],
       [-1.6683377 ,  1.718674  ],
       [-1.4558405 ,  1.5331231 ],
       [ 1.6207198 , -1.5807482 ],
       [-0.8750999 ,  1.0022148 ],
       [ 1.4334246 , -1.276626  ],
       [-0.11416343,  0.24619476],
       [-1.5979911 ,  1.6662685 ],
       [-1.6248752 ,  1.6657084 ],
       [-0.949271  ,  1.0276976 ],
       [ 0.20750658, -0.06354608],
       [ 1.4400396 , -1.2751025 ],
       [ 1.6276884 , -1.5977825 ],
       [-1.6132993 ,  1.6670328 ],
       [ 1.433897  , -1.2865484 ],
       [-1.2876698 ,  1.3720679 ],
       [ 1.4536017 , -1.3165616 ],
       [-1.5437391 ,  1.6215845 ],
       [ 0.8286166 , -0.6696024 ],
       [-1.6311312 ,  1.6622005 ],
       [-1.5541064 ,  1.5948203 ],
       [ 0.7663167 , -0.64429367],
       [-1.6494251 ,  1.7085162 ],
       [ 0.7381909 , -0.60649514],
       [ 1.5005695 , -1.358765  ],
       [ 1.6225373 , -1.5767034 ],
       [ 0.70578   , -0.5411942 ],
       [-0.4063781 ,  0.54061955],
       [-0.52188087,  0.6382328 ],
       [ 1.5134327 , -1.4000822 ],
       [-1.6592497 ,  1.7244824 ],
       [-0.6073711 ,  0.7048975 ],
       [ 0.07615133,  0.02170591],
       [-1.6449746 ,  1.6925246 ],
       [-1.5291749 ,  1.5682485 ],
       [ 1.5821939 , -1.4816868 ],
       [-1.6595577 ,  1.7102247 ],
       [-1.62593   ,  1.6346385 ],
       [-0.0812844 ,  0.2233554 ],
       [ 1.6087617 , -1.5528321 ],
       [-1.6547209 ,  1.6987685 ],
       [ 1.5757511 , -1.4726545 ],
       [ 1.6223925 , -1.5933846 ],
       [ 1.491679  , -1.3828226 ],
       [-0.5156592 ,  0.6171824 ],
       [ 1.6268847 , -1.581487  ],
       [-1.594433  ,  1.6367048 ],
       [ 0.36023796, -0.20675819],
       [ 1.5979065 , -1.5377266 ],
       [-1.6520883 ,  1.6889681 ],
       [-0.05078898,  0.16985872],
       [ 1.300852  , -1.1282588 ],
       [-0.32662848,  0.41971272],
       [ 1.4799124 , -1.330733  ],
       [ 0.82995033, -0.66715604],
       [-0.20120984,  0.32697597],
       [ 1.6113509 , -1.5491654 ],
       [-1.4933071 ,  1.5651436 ],
       [ 1.4016556 , -1.3105081 ],
       [-1.6072696 ,  1.6619078 ],
       [-1.6531224 ,  1.7076257 ],
       [-0.32134628,  0.42067924],
       [ 0.01187971,  0.12164789],
       [ 1.5197538 , -1.438284  ],
       [-1.6509131 ,  1.7084152 ],
       [-0.32303733,  0.4365292 ],
       [-0.16227204,  0.28956887],
       [-1.2298627 ,  1.3465819 ],
       [ 0.09923609,  0.02045331],
       [ 1.2103723 , -1.0464784 ],
       [ 1.528868  , -1.4149367 ],
       [-1.5609316 ,  1.6015813 ],
       [-0.09300001,  0.2736113 ],
       [ 1.5329524 , -1.4295453 ],
       [-1.6303324 ,  1.6559087 ],
       [ 1.1155318 , -0.94360125],
       [ 0.62504447, -0.46586213],
       [-1.110607  ,  1.1885331 ],
       [-1.6598982 ,  1.7053332 ],
       [ 0.33384892, -0.18657322],
       [-1.6415635 ,  1.6901675 ],
       [ 0.8214021 , -0.6663966 ],
       [ 1.6186272 , -1.5941122 ],
       [ 0.92171097, -0.7669534 ],
       [ 1.5832225 , -1.5070071 ],
       [-0.00596658,  0.13673499],
       [ 1.6126238 , -1.5463974 ],
       [-1.6458064 ,  1.6984597 ],
       [-0.27230197,  0.43584156],
       [ 1.1888546 , -0.9820558 ],
       [-1.6625273 ,  1.7079293 ],
       [-0.41530523,  0.5312807 ],
       [-1.0677515 ,  1.1475617 ],
       [ 1.4930845 , -1.3723093 ],
       [ 1.5638883 , -1.4795269 ],
       [ 0.67350525, -0.53387904],
       [ 1.2024251 , -1.0173761 ],
       [ 1.6306235 , -1.5930165 ],
       [ 1.6258796 , -1.5881993 ],
       [-1.458357  ,  1.5794812 ],
       [-1.6088111 ,  1.6515943 ],
       [ 1.2305168 , -1.0561266 ],
       [-0.3122899 ,  0.48163247],
       [ 1.3672665 , -1.2615917 ],
       [ 0.01589151,  0.11090812],
       [ 0.51694363, -0.43417853],
       [-0.8048945 ,  0.91724604],
       [ 1.1905679 , -1.0183884 ],
       [-0.9979084 ,  1.0923163 ],
       [-1.5771215 ,  1.6304657 ],
       [-1.0337292 ,  1.1457471 ],
       [-1.3247975 ,  1.3830086 ],
       [ 1.3696822 , -1.2573503 ],
       [-0.51608455,  0.63778293],
       [-1.6575568 ,  1.6998025 ],
       [-0.9368056 ,  1.0346509 ],
       [ 0.16070436, -0.00585511],
       [ 0.8458532 , -0.6834701 ],
       [ 0.589489  , -0.46759027],
       [ 1.608172  , -1.5501189 ],
       [-0.60225916,  0.7534771 ],
       [ 0.9265578 , -0.83319765],
       [ 1.2333345 , -1.0388851 ],
       [-1.6229541 ,  1.6691774 ],
       [ 1.2768644 , -1.0644559 ],
       [-0.27230197,  0.43584156],
       [ 0.97912973, -0.84223837],
       [-1.6538364 ,  1.7087705 ],
       [ 1.1547714 , -0.9968769 ],
       [ 1.3484663 , -1.1700273 ],
       [-1.6016244 ,  1.6402751 ],
       [-0.13964371,  0.26289403],
       [-1.2749945 ,  1.3627795 ],
       [ 0.14603929, -0.03761431],
       [-1.0809453 ,  1.1458232 ],
       [-0.29460248,  0.3965721 ],
       [ 1.5889556 , -1.5263158 ],
       [ 1.1882461 , -1.0138    ],
       [ 0.3129755 , -0.1595746 ],
       [ 1.2483519 , -1.0521466 ],
       [ 1.2119776 , -1.0238779 ],
       [ 0.31600928, -0.14501761],
       [ 0.6036961 , -0.44773477],
       [-1.0609794 ,  1.1256194 ],
       [-0.04372179,  0.1731008 ],
       [ 1.2247648 , -1.0327395 ],
       [ 0.06042865,  0.01786061],
       [-1.0606319 ,  1.1485409 ],
       [ 1.3771994 , -1.2258354 ],
       [-1.6672027 ,  1.7026001 ],
       [-1.2265743 ,  1.3207303 ],
       [ 1.5493338 , -1.4396523 ],
       [-1.4414018 ,  1.4740895 ],
       [ 1.2274005 , -1.0403221 ],
       [-1.4094695 ,  1.4813846 ],
       [ 0.30509365, -0.17001899],
       [-1.1429201 ,  1.2439734 ],
       [-1.4234873 ,  1.5035737 ],
       [ 0.87172616, -0.70865273],
       [ 1.3992331 , -1.2217265 ],
       [-0.9482464 ,  1.0611442 ],
       [-1.5214497 ,  1.577315  ],
       [-1.0250357 ,  1.1717612 ],
       [ 1.1242238 , -0.94656837],
       [ 1.5845789 , -1.503597  ],
       [ 1.0940776 , -0.90611494],
       [ 1.1811502 , -0.9907838 ],
       [-0.78656566,  0.90629977],
       [-0.7486273 ,  0.8152321 ],
       [-0.92173123,  0.9999232 ],
       [ 1.5647765 , -1.4942237 ],
       [ 1.1534089 , -0.97622436],
       [-0.19442572,  0.33078647],
       [-0.45433778,  0.58358777],
       [-0.45849043,  0.6051705 ],
       [-0.6335664 ,  0.79236495],
       [ 1.5993949 , -1.5408808 ],
       [-1.5881902 ,  1.6279887 ],
       [ 1.0538322 , -0.8967674 ],
       [-1.5538847 ,  1.5872201 ],
       [ 0.7441605 , -0.58406913],
       [-1.3995043 ,  1.4709349 ],
       [ 1.5064934 , -1.3553795 ],
       [ 1.6040477 , -1.5424367 ],
       [ 0.8602947 , -0.6980808 ],
       [ 0.1003585 ,  0.05585049],
       [-0.33986947,  0.4685875 ],
       [-0.81670403,  0.9058905 ],
       [ 1.0872345 , -0.9296029 ],
       [-1.1762131 ,  1.2452607 ],
       [-0.41405725,  0.5127516 ],
       [ 1.6163384 , -1.5845348 ],
       [-1.4792441 ,  1.526079  ],
       [-1.6424829 ,  1.6718247 ],
       [-1.6399328 ,  1.6939754 ],
       [-0.86396825,  0.960712  ],
       [-0.42652184,  0.52775997],
       [ 1.5555394 , -1.479693  ],
       [-1.6017715 ,  1.6402436 ],
       [-0.60544825,  0.758247  ],
       [ 0.71776056, -0.57392347],
       [-0.65844494,  0.7958342 ],
       [ 0.11112042, -0.00348519],
       [-0.7674446 ,  0.87612134],
       [-0.40460783,  0.5336253 ],
       [ 1.4352506 , -1.286517  ],
       [-1.6473855 ,  1.6831948 ],
       [ 0.9041455 , -0.7631355 ],
       [ 1.3714517 , -1.2311786 ],
       [ 0.5558139 , -0.39085442],
       [-1.2716516 ,  1.3688301 ],
       [ 1.6052543 , -1.5361829 ],
       [ 0.07904936,  0.04387525],
       [-1.3375174 ,  1.4267263 ],
       [ 1.2333226 , -1.0304192 ],
       [-1.5920004 ,  1.6152166 ],
       [ 1.5225048 , -1.4000069 ],
       [ 0.21260178, -0.07722607],
       [-1.1212295 ,  1.2404059 ],
       [ 1.552839  , -1.4687933 ],
       [ 0.5325751 , -0.3672738 ],
       [ 1.5406591 , -1.4337665 ],
       [ 1.5931128 , -1.5510215 ],
       [-1.2123495 ,  1.3300158 ],
       [ 1.6287172 , -1.5963354 ],
       [ 0.22202009, -0.05037089],
       [ 1.6009449 , -1.5442007 ],
       [ 1.5808839 , -1.4977163 ],
       [ 1.6291375 , -1.5956746 ],
       [ 1.2346233 , -1.0307086 ],
       [ 0.15225711, -0.00446332],
       [ 1.6281497 , -1.5840809 ],
       [-1.4539506 ,  1.4795243 ],
       [ 1.3711133 , -1.1887684 ],
       [ 1.2792289 , -1.0624753 ],
       [-0.7976241 ,  0.8846597 ],
       [ 1.4315554 , -1.2829736 ],
       [ 1.1190253 , -0.93835914],
       [-0.74412763,  0.89311063],
       [-1.5099565 ,  1.5575755 ],
       [ 1.6235262 , -1.5863453 ],
       [ 1.6057345 , -1.5517058 ],
       [ 1.6213344 , -1.5800341 ],
       [ 0.8267927 , -0.689474  ],
       [-1.6670536 ,  1.7139004 ],
       [-0.3987242 ,  0.54174364],
       [ 0.27114344, -0.14685771],
       [ 1.5669852 , -1.4775695 ],
       [-0.49271894,  0.64976656],
       [-0.789912  ,  0.9217366 ],
       [-0.75458336,  0.877923  ],
       [-1.3139948 ,  1.411918  ],
       [ 1.1854736 , -1.0005823 ],
       [ 1.5350839 , -1.4309007 ],
       [ 0.5536045 , -0.41673058],
       [ 1.3597013 , -1.19951   ],
       [ 1.6191205 , -1.5640603 ],
       [-1.177884  ,  1.2625016 ],
       [-0.2604639 ,  0.40205082],
       [ 1.4258254 , -1.2786742 ],
       [ 0.37118605, -0.23508188],
       [ 0.2323868 , -0.09132388],
       [-0.17699443,  0.29703218],
       [-1.5288473 ,  1.5598004 ],
       [ 0.23868552, -0.09397754],
       [-1.5495241 ,  1.5747386 ],
       [-0.21065226,  0.3398639 ],
       [-1.6478618 ,  1.7032789 ],
       [ 1.6149987 , -1.5597035 ],
       [-1.649113  ,  1.7031947 ],
       [ 1.6189612 , -1.5658902 ],
       [ 1.6307384 , -1.595054  ],
       [-0.29249826,  0.40688148],
       [ 1.4968772 , -1.3546422 ],
       [-1.6286311 ,  1.6834086 ],
       [ 1.5634694 , -1.4776748 ],
       [-1.6529752 ,  1.7007488 ],
       [ 0.85700846, -0.7212477 ],
       [ 1.1318132 , -0.94658005],
       [-1.5739013 ,  1.6158794 ],
       [ 1.6165209 , -1.575498  ],
       [ 1.5686558 , -1.4649318 ],
       [-0.9615799 ,  1.1151992 ],
       [ 1.5748551 , -1.4896233 ],
       [ 0.3576786 , -0.29360646],
       [ 0.16189224, -0.03819327],
       [-1.4137083 ,  1.5095855 ],
       [-0.36082992,  0.49944746],
       [-1.5200273 ,  1.5463172 ],
       [ 1.6153212 , -1.5589074 ],
       [ 0.11571373,  0.04442483],
       [ 0.28132045, -0.1519426 ],
       [-1.3751262 ,  1.4393977 ],
       [-0.25574762,  0.37580281],
       [-0.8877775 ,  0.9796474 ],
       [ 1.6187629 , -1.5823008 ],
       [ 1.6281577 , -1.5889915 ],
       [ 1.6136016 , -1.5639315 ],
       [-1.385367  ,  1.4254888 ],
       [ 1.5852581 , -1.5178872 ],
       [-1.6137931 ,  1.6502446 ],
       [ 1.1276911 , -0.9377014 ],
       [ 0.4036819 , -0.26832286],
       [ 1.548319  , -1.4415661 ],
       [ 1.0475792 , -0.8473566 ],
       [-1.0060419 ,  1.1458179 ],
       [ 1.5576061 , -1.4406528 ],
       [ 0.09537648,  0.08453972],
       [ 1.6219336 , -1.5725629 ],
       [-1.5759727 ,  1.6056072 ],
       [-1.4927158 ,  1.5251168 ],
       [ 0.12493863,  0.02697744],
       [ 1.5614394 , -1.4482666 ],
       [-0.3122899 ,  0.48163247],
       [-1.6721996 ,  1.7123879 ],
       [ 1.1395999 , -0.9801229 ],
       [-1.5879058 ,  1.6430292 ],
       [ 1.6283787 , -1.5925694 ],
       [-1.6398197 ,  1.6617976 ],
       [ 0.09749957,  0.0287116 ],
       [-0.778226  ,  0.8697931 ],
       [ 1.3506793 , -1.1748005 ],
       [ 0.79576606, -0.6378259 ],
       [ 1.5895413 , -1.540501  ],
       [-1.444223  ,  1.5163339 ],
       [-1.6596049 ,  1.7270954 ],
       [-0.27230197,  0.43584156],
       [-1.4168727 ,  1.4616685 ],
       [-1.3368849 ,  1.5292438 ],
       [ 1.6214732 , -1.5884598 ],
       [-0.02652064,  0.12746334],
       [-1.1549251 ,  1.2765077 ],
       [-1.4065398 ,  1.4943367 ],
       [ 0.70898056, -0.5583915 ],
       [ 0.05232719,  0.11343554],
       [ 0.54205954, -0.4300033 ],
       [-0.33214518,  0.44168845],
       [ 1.1092018 , -0.95299804],
       [ 0.47154498, -0.33963734],
       [ 0.61452967, -0.4710288 ],
       [ 1.5838373 , -1.5048944 ],
       [-0.27230197,  0.43584156],
       [ 1.6234231 , -1.5727826 ],
       [-1.6329545 ,  1.6952084 ],
       [ 0.64442486, -0.55764383],
       [ 1.547031  , -1.4405881 ],
       [-1.5022376 ,  1.5442269 ],
       [-0.75804704,  0.88208973],
       [ 1.2747047 , -1.0907851 ],
       [ 1.0593163 , -0.8899455 ],
       [-0.3281433 ,  0.45246863],
       [ 1.5307888 , -1.4372138 ],
       [-0.2731152 ,  0.4065174 ],
       [ 1.1933882 , -0.98721325],
       [-1.2966372 ,  1.3751688 ],
       [ 1.2811407 , -1.0769321 ],
       [-0.3718708 ,  0.53014874],
       [-1.1613406 ,  1.2813466 ],
       [-1.3526801 ,  1.4493122 ],
       [ 0.8614247 , -0.69693637],
       [-1.0531458 ,  1.1910037 ],
       [ 0.13937357,  0.00380204],
       [-1.5300709 ,  1.5807314 ],
       [ 0.79790246, -0.6381755 ],
       [-1.0015266 ,  1.1441622 ],
       [-1.5683964 ,  1.5866444 ],
       [-1.5751126 ,  1.5955125 ],
       [-1.6468905 ,  1.662712  ],
       [-0.27917242,  0.4063886 ],
       [-1.5864481 ,  1.6154714 ],
       [ 1.6252489 , -1.5650669 ],
       [ 1.6041595 , -1.540823  ],
       [ 1.6204183 , -1.5881224 ]], dtype=float32), label_ids=array([0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0]), metrics={'test_loss': 0.4788724482059479, 'test_runtime': 1.82, 'test_samples_per_second': 274.719, 'test_steps_per_second': 17.582})

In [20]:
y_logit = torch.tensor(prediction[0])
y_logit

tensor([[ 0.8486, -0.7298],
        [ 1.1592, -0.9619],
        [ 1.2762, -1.0967],
        [ 1.6204, -1.5558],
        [-0.4228,  0.5848],
        [ 1.6240, -1.5702],
        [-0.1536,  0.2955],
        [ 0.9487, -0.7644],
        [-1.6590,  1.7000],
        [ 1.0180, -0.8332],
        [-1.6679,  1.7211],
        [ 0.0068,  0.1548],
        [ 1.5637, -1.4600],
        [ 0.9830, -0.8271],
        [-0.0803,  0.2064],
        [ 1.2602, -1.0580],
        [ 1.6224, -1.5728],
        [-1.3425,  1.4738],
        [ 1.5970, -1.5315],
        [ 0.3299, -0.1722],
        [ 1.6146, -1.5677],
        [ 1.3626, -1.1988],
        [-0.0396,  0.2084],
        [ 0.0047,  0.1617],
        [ 1.5247, -1.4383],
        [ 1.1032, -0.9314],
        [ 0.6144, -0.4663],
        [-1.5086,  1.5305],
        [ 0.8880, -0.7447],
        [ 0.8468, -0.7095],
        [ 1.6078, -1.5452],
        [ 1.5947, -1.5525],
        [-1.5035,  1.5136],
        [-1.3732,  1.3930],
        [ 1.5993, -1.5574],
        [ 1.6133, -1.5561],
        [ 0.7028, -0.5896],
        [ 1.6185, -1.5575],
        [ 0.3203, -0.1618],
        [ 0.3661, -0.1849],
        [ 0.2524, -0.0813],
        [-1.6137,  1.6627],
        [-0.7574,  0.8826],
        [-1.6235,  1.6479],
        [ 1.1472, -0.9756],
        [-1.6334,  1.6994],
        [-1.6553,  1.6923],
        [ 1.6220, -1.5747],
        [-0.5892,  0.7345],
        [-1.5371,  1.5652],
        [-1.5465,  1.5528],
        [-1.6431,  1.6748],
        [ 0.5988, -0.4352],
        [ 1.5597, -1.4532],
        [ 1.5040, -1.3643],
        [ 1.5266, -1.4269],
        [-0.2370,  0.3810],
        [ 1.6204, -1.5701],
        [-1.5992,  1.6388],
        [-1.5303,  1.5567],
        [ 1.5890, -1.5063],
        [-1.3812,  1.4735],
        [ 0.7560, -0.5637],
        [ 0.1591,  0.0100],
        [-0.7296,  0.7893],
        [ 1.5944, -1.5205],
        [ 1.6280, -1.5884],
        [-0.4100,  0.5426],
        [-0.5314,  0.6380],
        [-0.0903,  0.2208],
        [ 1.6230, -1.5912],
        [-0.1567,  0.2608],
        [ 1.4668, -1.3392],
        [-0.3113,  0.4244],
        [-1.5583,  1.5912],
        [-0.4611,  0.5778],
        [-1.5082,  1.5302],
        [ 1.6211, -1.5836],
        [ 1.4196, -1.2497],
        [ 0.0635,  0.0438],
        [-1.3623,  1.4050],
        [-1.6482,  1.6843],
        [-1.6595,  1.7002],
        [-0.3123,  0.4816],
        [-1.6320,  1.6786],
        [ 0.4313, -0.2764],
        [-0.8344,  0.9462],
        [ 1.5748, -1.4962],
        [ 0.2527, -0.1210],
        [-0.7183,  0.8218],
        [ 0.9657, -0.7765],
        [-1.3551,  1.4542],
        [ 1.5768, -1.4910],
        [-1.1981,  1.3493],
        [ 1.6043, -1.5349],
        [-0.7529,  0.7714],
        [-0.2723,  0.4358],
        [ 0.1295,  0.0121],
        [ 1.6206, -1.5869],
        [ 0.9892, -0.8033],
        [-1.1386,  1.2773],
        [-0.3660,  0.4902],
        [-1.6374,  1.6848],
        [ 1.3614, -1.2126],
        [ 1.6146, -1.5721],
        [ 0.1731, -0.0401],
        [-1.3116,  1.4345],
        [ 1.6100, -1.5639],
        [ 1.4233, -1.2628],
        [ 0.4162, -0.2947],
        [-1.3183,  1.4137],
        [ 1.3999, -1.2331],
        [-0.5763,  0.6688],
        [-1.2689,  1.3716],
        [-0.5131,  0.5950],
        [ 0.0429,  0.0947],
        [ 0.0845,  0.0492],
        [-0.8186,  0.9410],
        [ 1.1173, -0.9267],
        [ 0.9236, -0.7517],
        [-0.0536,  0.1692],
        [-1.4160,  1.4590],
        [-0.1627,  0.2691],
        [-0.5707,  0.7107],
        [ 1.6252, -1.5914],
        [ 0.1139,  0.0255],
        [ 0.0135,  0.1212],
        [-1.6342,  1.6927],
        [-1.6683,  1.7187],
        [-1.4558,  1.5331],
        [ 1.6207, -1.5807],
        [-0.8751,  1.0022],
        [ 1.4334, -1.2766],
        [-0.1142,  0.2462],
        [-1.5980,  1.6663],
        [-1.6249,  1.6657],
        [-0.9493,  1.0277],
        [ 0.2075, -0.0635],
        [ 1.4400, -1.2751],
        [ 1.6277, -1.5978],
        [-1.6133,  1.6670],
        [ 1.4339, -1.2865],
        [-1.2877,  1.3721],
        [ 1.4536, -1.3166],
        [-1.5437,  1.6216],
        [ 0.8286, -0.6696],
        [-1.6311,  1.6622],
        [-1.5541,  1.5948],
        [ 0.7663, -0.6443],
        [-1.6494,  1.7085],
        [ 0.7382, -0.6065],
        [ 1.5006, -1.3588],
        [ 1.6225, -1.5767],
        [ 0.7058, -0.5412],
        [-0.4064,  0.5406],
        [-0.5219,  0.6382],
        [ 1.5134, -1.4001],
        [-1.6592,  1.7245],
        [-0.6074,  0.7049],
        [ 0.0762,  0.0217],
        [-1.6450,  1.6925],
        [-1.5292,  1.5682],
        [ 1.5822, -1.4817],
        [-1.6596,  1.7102],
        [-1.6259,  1.6346],
        [-0.0813,  0.2234],
        [ 1.6088, -1.5528],
        [-1.6547,  1.6988],
        [ 1.5758, -1.4727],
        [ 1.6224, -1.5934],
        [ 1.4917, -1.3828],
        [-0.5157,  0.6172],
        [ 1.6269, -1.5815],
        [-1.5944,  1.6367],
        [ 0.3602, -0.2068],
        [ 1.5979, -1.5377],
        [-1.6521,  1.6890],
        [-0.0508,  0.1699],
        [ 1.3009, -1.1283],
        [-0.3266,  0.4197],
        [ 1.4799, -1.3307],
        [ 0.8300, -0.6672],
        [-0.2012,  0.3270],
        [ 1.6114, -1.5492],
        [-1.4933,  1.5651],
        [ 1.4017, -1.3105],
        [-1.6073,  1.6619],
        [-1.6531,  1.7076],
        [-0.3213,  0.4207],
        [ 0.0119,  0.1216],
        [ 1.5198, -1.4383],
        [-1.6509,  1.7084],
        [-0.3230,  0.4365],
        [-0.1623,  0.2896],
        [-1.2299,  1.3466],
        [ 0.0992,  0.0205],
        [ 1.2104, -1.0465],
        [ 1.5289, -1.4149],
        [-1.5609,  1.6016],
        [-0.0930,  0.2736],
        [ 1.5330, -1.4295],
        [-1.6303,  1.6559],
        [ 1.1155, -0.9436],
        [ 0.6250, -0.4659],
        [-1.1106,  1.1885],
        [-1.6599,  1.7053],
        [ 0.3338, -0.1866],
        [-1.6416,  1.6902],
        [ 0.8214, -0.6664],
        [ 1.6186, -1.5941],
        [ 0.9217, -0.7670],
        [ 1.5832, -1.5070],
        [-0.0060,  0.1367],
        [ 1.6126, -1.5464],
        [-1.6458,  1.6985],
        [-0.2723,  0.4358],
        [ 1.1889, -0.9821],
        [-1.6625,  1.7079],
        [-0.4153,  0.5313],
        [-1.0678,  1.1476],
        [ 1.4931, -1.3723],
        [ 1.5639, -1.4795],
        [ 0.6735, -0.5339],
        [ 1.2024, -1.0174],
        [ 1.6306, -1.5930],
        [ 1.6259, -1.5882],
        [-1.4584,  1.5795],
        [-1.6088,  1.6516],
        [ 1.2305, -1.0561],
        [-0.3123,  0.4816],
        [ 1.3673, -1.2616],
        [ 0.0159,  0.1109],
        [ 0.5169, -0.4342],
        [-0.8049,  0.9172],
        [ 1.1906, -1.0184],
        [-0.9979,  1.0923],
        [-1.5771,  1.6305],
        [-1.0337,  1.1457],
        [-1.3248,  1.3830],
        [ 1.3697, -1.2574],
        [-0.5161,  0.6378],
        [-1.6576,  1.6998],
        [-0.9368,  1.0347],
        [ 0.1607, -0.0059],
        [ 0.8459, -0.6835],
        [ 0.5895, -0.4676],
        [ 1.6082, -1.5501],
        [-0.6023,  0.7535],
        [ 0.9266, -0.8332],
        [ 1.2333, -1.0389],
        [-1.6230,  1.6692],
        [ 1.2769, -1.0645],
        [-0.2723,  0.4358],
        [ 0.9791, -0.8422],
        [-1.6538,  1.7088],
        [ 1.1548, -0.9969],
        [ 1.3485, -1.1700],
        [-1.6016,  1.6403],
        [-0.1396,  0.2629],
        [-1.2750,  1.3628],
        [ 0.1460, -0.0376],
        [-1.0809,  1.1458],
        [-0.2946,  0.3966],
        [ 1.5890, -1.5263],
        [ 1.1882, -1.0138],
        [ 0.3130, -0.1596],
        [ 1.2484, -1.0521],
        [ 1.2120, -1.0239],
        [ 0.3160, -0.1450],
        [ 0.6037, -0.4477],
        [-1.0610,  1.1256],
        [-0.0437,  0.1731],
        [ 1.2248, -1.0327],
        [ 0.0604,  0.0179],
        [-1.0606,  1.1485],
        [ 1.3772, -1.2258],
        [-1.6672,  1.7026],
        [-1.2266,  1.3207],
        [ 1.5493, -1.4397],
        [-1.4414,  1.4741],
        [ 1.2274, -1.0403],
        [-1.4095,  1.4814],
        [ 0.3051, -0.1700],
        [-1.1429,  1.2440],
        [-1.4235,  1.5036],
        [ 0.8717, -0.7087],
        [ 1.3992, -1.2217],
        [-0.9482,  1.0611],
        [-1.5214,  1.5773],
        [-1.0250,  1.1718],
        [ 1.1242, -0.9466],
        [ 1.5846, -1.5036],
        [ 1.0941, -0.9061],
        [ 1.1812, -0.9908],
        [-0.7866,  0.9063],
        [-0.7486,  0.8152],
        [-0.9217,  0.9999],
        [ 1.5648, -1.4942],
        [ 1.1534, -0.9762],
        [-0.1944,  0.3308],
        [-0.4543,  0.5836],
        [-0.4585,  0.6052],
        [-0.6336,  0.7924],
        [ 1.5994, -1.5409],
        [-1.5882,  1.6280],
        [ 1.0538, -0.8968],
        [-1.5539,  1.5872],
        [ 0.7442, -0.5841],
        [-1.3995,  1.4709],
        [ 1.5065, -1.3554],
        [ 1.6040, -1.5424],
        [ 0.8603, -0.6981],
        [ 0.1004,  0.0559],
        [-0.3399,  0.4686],
        [-0.8167,  0.9059],
        [ 1.0872, -0.9296],
        [-1.1762,  1.2453],
        [-0.4141,  0.5128],
        [ 1.6163, -1.5845],
        [-1.4792,  1.5261],
        [-1.6425,  1.6718],
        [-1.6399,  1.6940],
        [-0.8640,  0.9607],
        [-0.4265,  0.5278],
        [ 1.5555, -1.4797],
        [-1.6018,  1.6402],
        [-0.6054,  0.7582],
        [ 0.7178, -0.5739],
        [-0.6584,  0.7958],
        [ 0.1111, -0.0035],
        [-0.7674,  0.8761],
        [-0.4046,  0.5336],
        [ 1.4353, -1.2865],
        [-1.6474,  1.6832],
        [ 0.9041, -0.7631],
        [ 1.3715, -1.2312],
        [ 0.5558, -0.3909],
        [-1.2717,  1.3688],
        [ 1.6053, -1.5362],
        [ 0.0790,  0.0439],
        [-1.3375,  1.4267],
        [ 1.2333, -1.0304],
        [-1.5920,  1.6152],
        [ 1.5225, -1.4000],
        [ 0.2126, -0.0772],
        [-1.1212,  1.2404],
        [ 1.5528, -1.4688],
        [ 0.5326, -0.3673],
        [ 1.5407, -1.4338],
        [ 1.5931, -1.5510],
        [-1.2123,  1.3300],
        [ 1.6287, -1.5963],
        [ 0.2220, -0.0504],
        [ 1.6009, -1.5442],
        [ 1.5809, -1.4977],
        [ 1.6291, -1.5957],
        [ 1.2346, -1.0307],
        [ 0.1523, -0.0045],
        [ 1.6281, -1.5841],
        [-1.4540,  1.4795],
        [ 1.3711, -1.1888],
        [ 1.2792, -1.0625],
        [-0.7976,  0.8847],
        [ 1.4316, -1.2830],
        [ 1.1190, -0.9384],
        [-0.7441,  0.8931],
        [-1.5100,  1.5576],
        [ 1.6235, -1.5863],
        [ 1.6057, -1.5517],
        [ 1.6213, -1.5800],
        [ 0.8268, -0.6895],
        [-1.6671,  1.7139],
        [-0.3987,  0.5417],
        [ 0.2711, -0.1469],
        [ 1.5670, -1.4776],
        [-0.4927,  0.6498],
        [-0.7899,  0.9217],
        [-0.7546,  0.8779],
        [-1.3140,  1.4119],
        [ 1.1855, -1.0006],
        [ 1.5351, -1.4309],
        [ 0.5536, -0.4167],
        [ 1.3597, -1.1995],
        [ 1.6191, -1.5641],
        [-1.1779,  1.2625],
        [-0.2605,  0.4021],
        [ 1.4258, -1.2787],
        [ 0.3712, -0.2351],
        [ 0.2324, -0.0913],
        [-0.1770,  0.2970],
        [-1.5288,  1.5598],
        [ 0.2387, -0.0940],
        [-1.5495,  1.5747],
        [-0.2107,  0.3399],
        [-1.6479,  1.7033],
        [ 1.6150, -1.5597],
        [-1.6491,  1.7032],
        [ 1.6190, -1.5659],
        [ 1.6307, -1.5951],
        [-0.2925,  0.4069],
        [ 1.4969, -1.3546],
        [-1.6286,  1.6834],
        [ 1.5635, -1.4777],
        [-1.6530,  1.7007],
        [ 0.8570, -0.7212],
        [ 1.1318, -0.9466],
        [-1.5739,  1.6159],
        [ 1.6165, -1.5755],
        [ 1.5687, -1.4649],
        [-0.9616,  1.1152],
        [ 1.5749, -1.4896],
        [ 0.3577, -0.2936],
        [ 0.1619, -0.0382],
        [-1.4137,  1.5096],
        [-0.3608,  0.4994],
        [-1.5200,  1.5463],
        [ 1.6153, -1.5589],
        [ 0.1157,  0.0444],
        [ 0.2813, -0.1519],
        [-1.3751,  1.4394],
        [-0.2557,  0.3758],
        [-0.8878,  0.9796],
        [ 1.6188, -1.5823],
        [ 1.6282, -1.5890],
        [ 1.6136, -1.5639],
        [-1.3854,  1.4255],
        [ 1.5853, -1.5179],
        [-1.6138,  1.6502],
        [ 1.1277, -0.9377],
        [ 0.4037, -0.2683],
        [ 1.5483, -1.4416],
        [ 1.0476, -0.8474],
        [-1.0060,  1.1458],
        [ 1.5576, -1.4407],
        [ 0.0954,  0.0845],
        [ 1.6219, -1.5726],
        [-1.5760,  1.6056],
        [-1.4927,  1.5251],
        [ 0.1249,  0.0270],
        [ 1.5614, -1.4483],
        [-0.3123,  0.4816],
        [-1.6722,  1.7124],
        [ 1.1396, -0.9801],
        [-1.5879,  1.6430],
        [ 1.6284, -1.5926],
        [-1.6398,  1.6618],
        [ 0.0975,  0.0287],
        [-0.7782,  0.8698],
        [ 1.3507, -1.1748],
        [ 0.7958, -0.6378],
        [ 1.5895, -1.5405],
        [-1.4442,  1.5163],
        [-1.6596,  1.7271],
        [-0.2723,  0.4358],
        [-1.4169,  1.4617],
        [-1.3369,  1.5292],
        [ 1.6215, -1.5885],
        [-0.0265,  0.1275],
        [-1.1549,  1.2765],
        [-1.4065,  1.4943],
        [ 0.7090, -0.5584],
        [ 0.0523,  0.1134],
        [ 0.5421, -0.4300],
        [-0.3321,  0.4417],
        [ 1.1092, -0.9530],
        [ 0.4715, -0.3396],
        [ 0.6145, -0.4710],
        [ 1.5838, -1.5049],
        [-0.2723,  0.4358],
        [ 1.6234, -1.5728],
        [-1.6330,  1.6952],
        [ 0.6444, -0.5576],
        [ 1.5470, -1.4406],
        [-1.5022,  1.5442],
        [-0.7580,  0.8821],
        [ 1.2747, -1.0908],
        [ 1.0593, -0.8899],
        [-0.3281,  0.4525],
        [ 1.5308, -1.4372],
        [-0.2731,  0.4065],
        [ 1.1934, -0.9872],
        [-1.2966,  1.3752],
        [ 1.2811, -1.0769],
        [-0.3719,  0.5301],
        [-1.1613,  1.2813],
        [-1.3527,  1.4493],
        [ 0.8614, -0.6969],
        [-1.0531,  1.1910],
        [ 0.1394,  0.0038],
        [-1.5301,  1.5807],
        [ 0.7979, -0.6382],
        [-1.0015,  1.1442],
        [-1.5684,  1.5866],
        [-1.5751,  1.5955],
        [-1.6469,  1.6627],
        [-0.2792,  0.4064],
        [-1.5864,  1.6155],
        [ 1.6252, -1.5651],
        [ 1.6042, -1.5408],
        [ 1.6204, -1.5881]])

In [21]:
y_pred = F.softmax(y_logit).argmax(axis=1).numpy()
y_pred

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(accuracy_score(y_test, y_pred))

cm=confusion_matrix(y_test, y_pred)
cm

0.79

array([[206,  52],
       [ 53, 189]])

In [23]:
x = '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나'
tokenized = tokenizer(x, truncation=True, padding=True)
tokenized

{'input_ids': [101, 100, 119, 119, 119, 9928, 58823, 30005, 11664, 9757, 118823, 30858, 18227, 119219, 119, 119, 119, 119, 9580, 41605, 25486, 12310, 20626, 23466, 8843, 118986, 12508, 9523, 17196, 16439, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [24]:
tokenizer.decode(tokenized['input_ids'])

'[CLS] [UNK]... 포스터보고 초딩영화줄.... 오버연기조차 가볍지 않구나 [SEP]'

In [66]:
input_ids = torch.tensor(tokenized['input_ids'])
attention_mask = torch.tensor(tokenized['attention_mask'])

In [67]:
model(input_ids, attention_mask)

ValueError: ignored